# Версия Docker API
version: '3.8'
services:
# Первый сервис (имя)
  mysqlService:
# Образ на основе которого он будет запускаться
    image: mysql:8.0.25
    # Пробросить порт 3306 хоста в порт 3306 контейнера
    ports:
      - 3306:3306
    #  механизм, позволяющий "пробрасывать" каталоги в контейнер
    #  из локального каталога "resources" для проброски файлов в специальный каталог этого образа для начальной инициализации (т.е. если туда положить файлы нужного формата, то база данных при старте их будет считывать).
    volumes:
      - ./resources/schema:/docker-entrypoint-initdb.d
    # Переменные окружения
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
